# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
# Created by: PyQt4 UI code generator 4.8.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(989, 912)
        self.gridLayout_2 = QtGui.QGridLayout(Dialog)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridlayout = QtGui.QGridLayout()
        self.gridlayout.setObjectName(_fromUtf8("gridlayout"))
        self.checkBox_31 = QtGui.QCheckBox(Dialog)
        self.checkBox_31.setObjectName(_fromUtf8("checkBox_31"))
        self.gridlayout.addWidget(self.checkBox_31, 15, 1, 1, 1)
        self.checkBox_30 = QtGui.QCheckBox(Dialog)
        self.checkBox_30.setObjectName(_fromUtf8("checkBox_30"))
        self.gridlayout.addWidget(self.checkBox_30, 14, 1, 1, 1)
        self.checkBox_29 = QtGui.QCheckBox(Dialog)
        self.checkBox_29.setObjectName(_fromUtf8("checkBox_29"))
        self.gridlayout.addWidget(self.checkBox_29, 13, 1, 1, 1)
        self.checkBox_28 = QtGui.QCheckBox(Dialog)
        self.checkBox_28.setObjectName(_fromUtf8("checkBox_28"))
        self.gridlayout.addWidget(self.checkBox_28, 12, 1, 1, 1)
        self.checkBox_27 = QtGui.QCheckBox(Dialog)
        self.checkBox_27.setObjectName(_fromUtf8("checkBox_27"))
        self.gridlayout.addWidget(self.checkBox_27, 11, 1, 1, 1)
        self.checkBox_26 = QtGui.QCheckBox(Dialog)
        self.checkBox_26.setObjectName(_fromUtf8("checkBox_26"))
        self.gridlayout.addWidget(self.checkBox_26, 10, 1, 1, 1)
        self.checkBox_25 = QtGui.QCheckBox(Dialog)
        self.checkBox_25.setObjectName(_fromUtf8("checkBox_25"))
        self.gridlayout.addWidget(self.checkBox_25, 9, 1, 1, 1)
        self.checkBox_24 = QtGui.QCheckBox(Dialog)
        self.checkBox_24.setObjectName(_fromUtf8("checkBox_24"))
        self.gridlayout.addWidget(self.checkBox_24, 8, 1, 1, 1)
        self.checkBox_23 = QtGui.QCheckBox(Dialog)
        self.checkBox_23.setObjectName(_fromUtf8("checkBox_23"))
        self.gridlayout.addWidget(self.checkBox_23, 7, 1, 1, 1)
        self.checkBox_22 = QtGui.QCheckBox(Dialog)
        self.checkBox_22.setObjectName(_fromUtf8("checkBox_22"))
        self.gridlayout.addWidget(self.checkBox_22, 6, 1, 1, 1)
        self.checkBox_21 = QtGui.QCheckBox(Dialog)
        self.checkBox_21.setObjectName(_fromUtf8("checkBox_21"))
        self.gridlayout.addWidget(self.checkBox_21, 5, 1, 1, 1)
        self.checkBox_20 = QtGui.QCheckBox(Dialog)
        self.checkBox_20.setObjectName(_fromUtf8("checkBox_20"))
        self.gridlayout.addWidget(self.checkBox_20, 4, 1, 1, 1)
        self.checkBox_19 = QtGui.QCheckBox(Dialog)
        self.checkBox_19.setObjectName(_fromUtf8("checkBox_19"))
        self.gridlayout.addWidget(self.checkBox_19, 3, 1, 1, 1)
        self.checkBox_18 = QtGui.QCheckBox(Dialog)
        self.checkBox_18.setObjectName(_fromUtf8("checkBox_18"))
        self.gridlayout.addWidget(self.checkBox_18, 2, 1, 1, 1)
        self.checkBox_17 = QtGui.QCheckBox(Dialog)
        self.checkBox_17.setObjectName(_fromUtf8("checkBox_17"))
        self.gridlayout.addWidget(self.checkBox_17, 1, 1, 1, 1)
        self.checkBox_16 = QtGui.QCheckBox(Dialog)
        self.checkBox_16.setObjectName(_fromUtf8("checkBox_16"))
        self.gridlayout.addWidget(self.checkBox_16, 0, 1, 1, 1)
        self.checkBox_15 = QtGui.QCheckBox(Dialog)
        self.checkBox_15.setObjectName(_fromUtf8("checkBox_15"))
        self.gridlayout.addWidget(self.checkBox_15, 15, 0, 1, 1)
        self.checkBox_14 = QtGui.QCheckBox(Dialog)
        self.checkBox_14.setObjectName(_fromUtf8("checkBox_14"))
        self.gridlayout.addWidget(self.checkBox_14, 14, 0, 1, 1)
        self.checkBox_13 = QtGui.QCheckBox(Dialog)
        self.checkBox_13.setObjectName(_fromUtf8("checkBox_13"))
        self.gridlayout.addWidget(self.checkBox_13, 13, 0, 1, 1)
        self.checkBox_12 = QtGui.QCheckBox(Dialog)
        self.checkBox_12.setObjectName(_fromUtf8("checkBox_12"))
        self.gridlayout.addWidget(self.checkBox_12, 12, 0, 1, 1)
        self.checkBox_11 = QtGui.QCheckBox(Dialog)
        self.checkBox_11.setObjectName(_fromUtf8("checkBox_11"))
        self.gridlayout.addWidget(self.checkBox_11, 11, 0, 1, 1)
        self.checkBox_10 = QtGui.QCheckBox(Dialog)
        self.checkBox_10.setObjectName(_fromUtf8("checkBox_10"))
        self.gridlayout.addWidget(self.checkBox_10, 10, 0, 1, 1)
        self.checkBox_9 = QtGui.QCheckBox(Dialog)
        self.checkBox_9.setObjectName(_fromUtf8("checkBox_9"))
        self.gridlayout.addWidget(self.checkBox_9, 9, 0, 1, 1)
        self.checkBox_8 = QtGui.QCheckBox(Dialog)
        self.checkBox_8.setObjectName(_fromUtf8("checkBox_8"))
        self.gridlayout.addWidget(self.checkBox_8, 8, 0, 1, 1)
        self.checkBox_7 = QtGui.QCheckBox(Dialog)
        self.checkBox_7.setObjectName(_fromUtf8("checkBox_7"))
        self.gridlayout.addWidget(self.checkBox_7, 7, 0, 1, 1)
        self.checkBox_6 = QtGui.QCheckBox(Dialog)
        self.checkBox_6.setObjectName(_fromUtf8("checkBox_6"))
        self.gridlayout.addWidget(self.checkBox_6, 6, 0, 1, 1)
        self.checkBox_5 = QtGui.QCheckBox(Dialog)
        self.checkBox_5.setObjectName(_fromUtf8("checkBox_5"))
        self.gridlayout.addWidget(self.checkBox_5, 5, 0, 1, 1)
        self.checkBox_4 = QtGui.QCheckBox(Dialog)
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.gridlayout.addWidget(self.checkBox_4, 4, 0, 1, 1)
        self.checkBox_3 = QtGui.QCheckBox(Dialog)
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.gridlayout.addWidget(self.checkBox_3, 3, 0, 1, 1)
        self.checkBox_2 = QtGui.QCheckBox(Dialog)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.gridlayout.addWidget(self.checkBox_2, 2, 0, 1, 1)
        self.checkBox_1 = QtGui.QCheckBox(Dialog)
        self.checkBox_1.setObjectName(_fromUtf8("checkBox_1"))
        self.gridlayout.addWidget(self.checkBox_1, 1, 0, 1, 1)
        self.checkBox = QtGui.QCheckBox(Dialog)
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.gridlayout.addWidget(self.checkBox, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridlayout, 5, 5, 1, 2)
        self.iterationBox = QtGui.QSpinBox(Dialog)
        self.iterationBox.setMinimumSize(QtCore.QSize(100, 0))
        self.iterationBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.iterationBox.setMaximum(9999999)
        self.iterationBox.setProperty(_fromUtf8("value"), 32)
        self.iterationBox.setObjectName(_fromUtf8("iterationBox"))
        self.gridLayout_2.addWidget(self.iterationBox, 6, 5, 1, 1)
        self.pushButton_add = QtGui.QPushButton(Dialog)
        self.pushButton_add.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_add.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_add.setObjectName(_fromUtf8("pushButton_add"))
        self.gridLayout_2.addWidget(self.pushButton_add, 6, 6, 1, 1)
        self.listWidget = QtGui.QListWidget(Dialog)
        self.listWidget.setMinimumSize(QtCore.QSize(400, 90))
        self.listWidget.setMaximumSize(QtCore.QSize(800, 200))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_2.addWidget(self.listWidget, 10, 0, 1, 7)
        self.label_6 = QtGui.QLabel(Dialog)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 9, 0, 1, 2)
        self.label_7 = QtGui.QLabel(Dialog)
        self.label_7.setMinimumSize(QtCore.QSize(100, 0))
        self.label_7.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 4, 5, 1, 1)
        self.label = QtGui.QLabel(Dialog)
        self.label.setMinimumSize(QtCore.QSize(200, 0))
        self.label.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.lineEdit_db = QtGui.QLineEdit(Dialog)
        self.lineEdit_db.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_db.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_db.setObjectName(_fromUtf8("lineEdit_db"))
        self.gridLayout_2.addWidget(self.lineEdit_db, 1, 0, 1, 2)
        self.label_2 = QtGui.QLabel(Dialog)
        self.label_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 2, 1, 2)
        self.lineEdit_6 = QtGui.QLineEdit(Dialog)
        self.lineEdit_6.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_6.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_6.setObjectName(_fromUtf8("lineEdit_6"))
        self.gridLayout_2.addWidget(self.lineEdit_6, 1, 2, 1, 2)
        self.pushButton_reLogin = QtGui.QPushButton(Dialog)
        self.pushButton_reLogin.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_reLogin.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_reLogin.setAutoDefault(False)
        self.pushButton_reLogin.setObjectName(_fromUtf8("pushButton_reLogin"))
        self.gridLayout_2.addWidget(self.pushButton_reLogin, 1, 4, 1, 1)
        self.label_3 = QtGui.QLabel(Dialog)
        self.label_3.setMinimumSize(QtCore.QSize(200, 0))
        self.label_3.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 2)
        self.label_4 = QtGui.QLabel(Dialog)
        self.label_4.setMinimumSize(QtCore.QSize(200, 0))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 2, 1, 2)
        self.comboBox_4 = QtGui.QComboBox(Dialog)
        self.comboBox_4.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_4.setObjectName(_fromUtf8("comboBox_4"))
        self.gridLayout_2.addWidget(self.comboBox_4, 3, 0, 1, 2)
        self.comboBox_5 = QtGui.QComboBox(Dialog)
        self.comboBox_5.setMinimumSize(QtCore.QSize(200, 0))
        self.comboBox_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_5.setObjectName(_fromUtf8("comboBox_5"))
        self.gridLayout_2.addWidget(self.comboBox_5, 3, 2, 1, 2)
        self.pushButton_saveAs = QtGui.QPushButton(Dialog)
        self.pushButton_saveAs.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_saveAs.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_saveAs.setAutoDefault(False)
        self.pushButton_saveAs.setObjectName(_fromUtf8("pushButton_saveAs"))
        self.gridLayout_2.addWidget(self.pushButton_saveAs, 12, 3, 1, 1)
        self.pushButton_exit = QtGui.QPushButton(Dialog)
        self.pushButton_exit.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_exit.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_exit.setAutoDefault(False)
        self.pushButton_exit.setObjectName(_fromUtf8("pushButton_exit"))
        self.gridLayout_2.addWidget(self.pushButton_exit, 12, 4, 1, 1)
        self.label_5 = QtGui.QLabel(Dialog)
        self.label_5.setMinimumSize(QtCore.QSize(200, 0))
        self.label_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 11, 0, 1, 2)
        self.lineEdit_4 = QtGui.QLineEdit(Dialog)
        self.lineEdit_4.setMinimumSize(QtCore.QSize(100, 0))
        self.lineEdit_4.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.gridLayout_2.addWidget(self.lineEdit_4, 12, 0, 1, 2)
        self.pushButton_save = QtGui.QPushButton(Dialog)
        self.pushButton_save.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_save.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_save.setAutoDefault(False)
        self.pushButton_save.setObjectName(_fromUtf8("pushButton_save"))
        self.gridLayout_2.addWidget(self.pushButton_save, 12, 2, 1, 1)
        self.pushButton_search = QtGui.QPushButton(Dialog)
        self.pushButton_search.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_search.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_search.setAutoDefault(False)
        self.pushButton_search.setObjectName(_fromUtf8("pushButton_search"))
        self.gridLayout_2.addWidget(self.pushButton_search, 7, 0, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(Dialog)
        self.listWidget_2.setMinimumSize(QtCore.QSize(100, 40))
        self.listWidget_2.setMaximumSize(QtCore.QSize(200, 40))
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_2.addWidget(self.listWidget_2, 7, 5, 1, 1)
        self.pushButton_del_hi_sel = QtGui.QPushButton(Dialog)
        self.pushButton_del_hi_sel.setMinimumSize(QtCore.QSize(100, 0))
        self.pushButton_del_hi_sel.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_del_hi_sel.setAutoDefault(False)
        self.pushButton_del_hi_sel.setObjectName(_fromUtf8("pushButton_del_hi_sel"))
        self.gridLayout_2.addWidget(self.pushButton_del_hi_sel, 7, 6, 1, 1)
        self.tableWidget = QtGui.QTableWidget(Dialog)
        self.tableWidget.setMinimumSize(QtCore.QSize(400, 200))
        self.tableWidget.setMaximumSize(QtCore.QSize(600, 500))
        self.tableWidget.setObjectName(_fromUtf8("tableWidget"))
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_2.addWidget(self.tableWidget, 4, 0, 3, 5)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "Dialog", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_31.setText(QtGui.QApplication.translate("Dialog", "31", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_30.setText(QtGui.QApplication.translate("Dialog", "30", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_29.setText(QtGui.QApplication.translate("Dialog", "29", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_28.setText(QtGui.QApplication.translate("Dialog", "28", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_27.setText(QtGui.QApplication.translate("Dialog", "27", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_26.setText(QtGui.QApplication.translate("Dialog", "26", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_25.setText(QtGui.QApplication.translate("Dialog", "25", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_24.setText(QtGui.QApplication.translate("Dialog", "24", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_23.setText(QtGui.QApplication.translate("Dialog", "23", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_22.setText(QtGui.QApplication.translate("Dialog", "22", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_21.setText(QtGui.QApplication.translate("Dialog", "21", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_20.setText(QtGui.QApplication.translate("Dialog", "20", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_19.setText(QtGui.QApplication.translate("Dialog", "19", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_18.setText(QtGui.QApplication.translate("Dialog", "18", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_17.setText(QtGui.QApplication.translate("Dialog", "17", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_16.setText(QtGui.QApplication.translate("Dialog", "16", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_15.setText(QtGui.QApplication.translate("Dialog", "15", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_14.setText(QtGui.QApplication.translate("Dialog", "14", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_13.setText(QtGui.QApplication.translate("Dialog", "13", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_12.setText(QtGui.QApplication.translate("Dialog", "12", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_11.setText(QtGui.QApplication.translate("Dialog", "11", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_10.setText(QtGui.QApplication.translate("Dialog", "10", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_9.setText(QtGui.QApplication.translate("Dialog", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_8.setText(QtGui.QApplication.translate("Dialog", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_7.setText(QtGui.QApplication.translate("Dialog", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_6.setText(QtGui.QApplication.translate("Dialog", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_5.setText(QtGui.QApplication.translate("Dialog", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_4.setText(QtGui.QApplication.translate("Dialog", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_3.setText(QtGui.QApplication.translate("Dialog", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_2.setText(QtGui.QApplication.translate("Dialog", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox_1.setText(QtGui.QApplication.translate("Dialog", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.checkBox.setText(QtGui.QApplication.translate("Dialog", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.iterationBox.setToolTip(QtGui.QApplication.translate("Dialog", "Type in any number and press [RETURN]", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_add.setText(QtGui.QApplication.translate("Dialog", "Add", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("Dialog", "Results", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("Dialog", "Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Database", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Dialog", "User", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_reLogin.setText(QtGui.QApplication.translate("Dialog", "Login", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Dialog", "Chain", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Dialog", "Result Type", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_saveAs.setText(QtGui.QApplication.translate("Dialog", "Save As", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_exit.setText(QtGui.QApplication.translate("Dialog", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("Dialog", "Create Matlab-Script", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_save.setText(QtGui.QApplication.translate("Dialog", "Save", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_search.setText(QtGui.QApplication.translate("Dialog", "Search", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_del_hi_sel.setText(QtGui.QApplication.translate("Dialog", "Delete Iterations", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Dialog", "Parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.tableWidget.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Dialog", "Wert", None, QtGui.QApplication.UnicodeUTF8))

